---
- name: Consul Playbook
  hosts: all
  become: True

  tasks:
  - name: Install yum-utils, bind-utils, epel-release and nginx
    yum:
      name: "{{ item }}"
      state: present
      update_cache: True
    loop:
    - yum-utils
    - bind-utils
    - epel-release
    - nginx
  - name: Add consul repository
    shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  - name: Install consul
    yum:
      name: consul
      state: present
      update_cache: True
