- hosts: all
  become: True
  tasks:
    - name: Install yum-utils
      yum:
        name: yum-utils
        state: present
        update_cache: True
    - name: Install bind utils
      yum:
        name: bind-utils
        state: present
        update_cache: True
    - name: Install epe-release
      yum:
        name: epel-release
        state: present
        cache_update: True
    - name: Install nginx
      yum:
        name: nginx
        state: present
        cache_update: True    
    - name: Add consul repository
      shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    - name: Install consul
      yum:
        name: consul
        state: present
        update_cache: True
